/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxyGlbRouteImport } from './routes/api/proxy-glb'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as App3dModelsRouteImport } from './routes/_app/3d-models'
import { Route as AppVideosIndexRouteImport } from './routes/_app/videos/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppImagesIndexRouteImport } from './routes/_app/images/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyGlbRoute = ApiProxyGlbRouteImport.update({
  id: '/api/proxy-glb',
  path: '/api/proxy-glb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const App3dModelsRoute = App3dModelsRouteImport.update({
  id: '/3d-models',
  path: '/3d-models',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosIndexRoute = AppVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesIndexRoute = AppImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/3d-models': typeof App3dModelsRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy-glb': typeof ApiProxyGlbRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/images': typeof AppImagesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/videos': typeof AppVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/3d-models': typeof App3dModelsRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy-glb': typeof ApiProxyGlbRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/images': typeof AppImagesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/videos': typeof AppVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_app/3d-models': typeof App3dModelsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy-glb': typeof ApiProxyGlbRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/images/': typeof AppImagesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/videos/': typeof AppVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/3d-models'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/api/proxy-glb'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/images'
    | '/projects'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/3d-models'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/signup'
    | '/api/chat'
    | '/api/proxy-glb'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/images'
    | '/projects'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/pricing'
    | '/_app/3d-models'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/chat'
    | '/api/proxy-glb'
    | '/_app/projects/$projectId'
    | '/api/auth/$'
    | '/_app/images/'
    | '/_app/projects/'
    | '/_app/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProxyGlbRoute: typeof ApiProxyGlbRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-glb': {
      id: '/api/proxy-glb'
      path: '/api/proxy-glb'
      fullPath: '/api/proxy-glb'
      preLoaderRoute: typeof ApiProxyGlbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/3d-models': {
      id: '/_app/3d-models'
      path: '/3d-models'
      fullPath: '/3d-models'
      preLoaderRoute: typeof App3dModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos/': {
      id: '/_app/videos/'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images/': {
      id: '/_app/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AppImagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  App3dModelsRoute: typeof App3dModelsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppImagesIndexRoute: typeof AppImagesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppVideosIndexRoute: typeof AppVideosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  App3dModelsRoute: App3dModelsRoute,
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppImagesIndexRoute: AppImagesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppVideosIndexRoute: AppVideosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProxyGlbRoute: ApiProxyGlbRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
